### ISSUE TITLE
makeExtendSchemaPlugin and resolveInfo confusion

### ISSUE THREAD

**Issue by petetnt** [graphile/graphile.github.io#104]
Hey!

I am running into this issue/question with Postgraphile 4.2.0 and @4.0.0-rc5.

I am building a custom schema for an app and I would like to use `resolveInfo.graphile.selectGraphQLResultFromTable` to select items from the table. As seen in the [docs](https://www.graphile.org/postgraphile/make-extend-schema-plugin/), it seems that using the fifth argument is now encouraged and instead it's recommended to use the fourth argument

```js
        randomUser: async (
          _query,
          args,
          context,
          resolveInfo
        ) => { resolveInfo.graphile.selectGraphQLResultFromTable(...) // fails :( }
```

However, it seems that the fourth argument _does not_ currently contain the `graphile` object, but the fifth argument works just fine:

```js
        randomUser: async (
          _query,
          args,
          context,
          _,
          graphile
        ) =>{ graphile.selectGraphQLResultFromTable(...) // works! }
```

Is the issue in the code or in the docs, or am I just running into some unrelated issue? Happy to send a PR if this is a real issue.

Thanks for your time and effort!

**Comment by benjie** [comment]
It’s preferable to use the 4th argument; the 5th will be removed in v5. Could you send me a minimal plugin I can reproduce the issue with? Also check against 4.3.0 (just released under `@next` tag).

Please include exact error messages when reporting issues rather than “fails”, it really aids figuring out what went wrong :)

**Comment by petetnt** [comment]
Argh, sorry about that @benjie, thought that I pasted the whole thing! Getting bit late. By fails, I mean that it doesn't exist in the object. Also occurs in postgraphile@next (4.3.0)

Quick example:

Typedef:

```graphql
const types = `
  extend type Query {
    fooQuery(address: String!, groupBy: String = "1h"): Foo
  }
 
  type Foo {
      foobar: String
   }
`;
```

```js
const resolvers = build => ({
  Query: {
    foobarQuery: async (
      query,
      args,
      context,
      fourth,
      fifth
    ) => {
      console.log({
        fourth,
        fifth,
      });

      return {
          foobar: "foobar"
      };
    },
  },
});
```

The fourth parameter:

```
   { fieldName: 'buildingDataByAddress',
     fieldNodes: [ [Object] ],
     returnType: BuildingData,
     parentType: Query,
     path: { prev: undefined, key: 'foobarQuery' },
     schema:
      GraphQLSchema {
        __allowedLegacyNames: undefined,
        _queryType: Query,
        _mutationType: Mutation,
        _subscriptionType: undefined,
        _directives: [Array],
        astNode: undefined,
        _typeMap: [Object],
        _implementations: [Object],
        __validationErrors: [] },
     fragments: {},
     rootValue: null,
     operation:
      { kind: 'OperationDefinition',
        operation: 'query',
        name: undefined,
        variableDefinitions: [Array],
        directives: [],
        selectionSet: [Object],
        loc: [Object] },
     variableValues: { _v0_address: 'address', _v1_groupBy: '1h' } }
```

The fifth parameter:
```
   { type: 'GraphQLObjectType',
     scope:
      { __origin: 'graphile-build built-in (root query type)',
        isRootQuery: true,
        fieldName: 'buildingDataByAddress',
        fieldDirectives: {},
        [Symbol(hints)]: [Object] },
     Self: Query,
     addDataGenerator: [Function: addDataGenerator],
     addArgDataGenerator: [Function: addArgDataGenerator],
     getDataFromParsedResolveInfoFragment: [Function: getDataFromParsedResolveInfoFragment],
     selectGraphQLResultFromTable: [AsyncFunction: selectGraphQLResultFromTable] } }
{ type: 'GraphQLObjectType',
  scope:
   { __origin: 'graphile-build built-in (root query type)',
     isRootQuery: true,
     fieldName: 'foobarQuery',
     fieldDirectives: {},
     [Symbol(hints)]:
      { fieldName: 'Within context for GraphQLObjectType \'Query\'',
        fieldDirectives: 'Extending scope for field \'foobarQuery\' within context for GraphQLObjectType \'Query\'' } },
  Self: Query,
  addDataGenerator: [Function: addDataGenerator],
  addArgDataGenerator: [Function: addArgDataGenerator],
  getDataFromParsedResolveInfoFragment: [Function: getDataFromParsedResolveInfoFragment],
  selectGraphQLResultFromTable: [AsyncFunction: selectGraphQLResultFromTable] }
```

Expected would be that `fourth` would contain the `graphile` object that would contain the `selectGraphQLResultFromTable` method.

Just a sec and I can whip an example plugin.

**Comment by petetnt** [comment]
Here's an minimal plugin that showcases the issue:

https://github.com/petetnt/postgraphile-issue-104

**Comment by benjie** [comment]
It was introduced in this commit:

https://github.com/graphile/graphile-engine/commit/e8df093ac3c8c76cbe3015950a074a274e825540#diff-6382050745079f4f8fa3e718629ea8b7

which should be in 4.1.0+

**Comment by benjie** [comment]
(You do need to upgrade graphile-utils to 4.1.0 separately, it's technically an independent module currently.)

**Comment by petetnt** [comment]
Ah, upgrading graphile-utils solved the issue. Should have thought of that. Thanks once again!
