### ISSUE TITLE
need a better example of doing a direct postgres query

### ISSUE THREAD

**Issue by maxharris9** [graphile/graphile.github.io#127]
it's nearly impossible to figure out how to directly query pg from inside a graphql resolver just by reading the docs.

an example similar to this would help:
```
Query: { // NB: it was _separately_ hard to figure out that I needed to put this under the `Query` key
  someResolver: async (root, args, context, info) => {
  const {rows: [dependency]} = await context.pgClient.query('select * from graphql.somepostgresfunc($1, $2, $3)', [args.first, args.second, args.third]);
  return {
    dependency
  }
}
```

**Comment by garcianavalon** [comment]
@benjie  Where in the docs could this be added? Maybe in [make-extend-schema-plugin](https://www.graphile.org/postgraphile/make-extend-schema-plugin/)?

**Comment by benjie** [comment]
I think that would make sense :+1:
