### ISSUE TITLE
Highlighting in examples wraps poorly

### ISSUE THREAD

**Issue by cbandy** [graphile/graphile.github.io#156]
The published site wraps lines in this example in a way that is difficult for me to read. (I must scroll to the right to read the fourth line. It appears to be many lines joined together?)

<img width="834" alt="Screen Shot 2019-08-23 at 1 39 20 PM" src="https://user-images.githubusercontent.com/106560/63615772-ba77be80-c5ab-11e9-9919-00cdd16a9ee6.png">

I thought it might be quick for me to fix, but it looks alright when I checkout the `develop` branch locally:

<img width="756" alt="Screen Shot 2019-08-23 at 1 38 38 PM" src="https://user-images.githubusercontent.com/106560/63615859-ed21b700-c5ab-11e9-9616-ebc44c2bf630.png">

It seems as though the lines that should be highlighted are the affected ones.

**Comment by benjie** [comment]
We’ve had this issue before but I am not seeing it currently; could you try clearing your caches and reloading? If that fails, try navigating to a different page, reloading, and then navigating back. I’ve lost best part of a day to this in the past, something is broken in Gatsby’s code highlighting and I managed to work around it with a forced re-render after a short delay. Definitely a hack though; perhaps upgrading gatsby will fix it.

And yes, like all good bugs it only happens in production. 🙄

**Comment by benjie** [comment]
That’s the worst kind of bug. Pretty sure it’s a Gatsby / GitHub Pages / caching issue.

**Comment by connorholyday** [comment]
There's an umbrella issue on the Gatsby Repo for [caching issues](https://github.com/gatsbyjs/gatsby/issues/11747) and the general consensus is to run the `gatsby clean` [command](https://www.gatsbyjs.org/docs/debugging-cache-issues/) before building; as can be seen in the [Gatsby Netlify CMS Starter](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/package.json#L40%E2%80%AC). Might be worth trying out?

**Comment by benjie** [comment]
From my experience that makes things much worse than just messed up linebreaks.

**Comment by benjie** [comment]
I've upgraded all the dependencies and have not noticed the issue again, so I am closing this. Please re-open if you see it again.
