### ISSUE TITLE
How is this software licensed?

### ISSUE THREAD

**Issue by guyjacks** [graphile/graphile.github.io#159]
I can't find the license for this project.

![Screen Shot 2019-09-04 at 2 00 14 PM](https://user-images.githubusercontent.com/6286429/64279210-804bdc80-cf1c-11e9-907f-145d472e621d.png)

**Comment by benjie** [comment]
Is there a specific piece of software in this, our website repository, that you're interested in? Most of this repo is content and configuration rather than unique software.

**Comment by guyjacks** [comment]
I didn't realize this wasn't the primary repo for Graphile.  Feel free to delete.

**Comment by benjie** [comment]
No problem, I suspected that might be the case. 👍
