### ISSUE TITLE
[not graphile related] check char_length < N VS character varying (N)

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile.github.io#16]
In [the documentation](https://github.com/graphile/graphile.github.io/blob/e1e59d10a79636c28e9ee670024c0484278673b9/src/pages/postgraphile/postgresql-schema-design.md#the-person-table) I’ve noticed the length of `first_name` and `last_name` is validated with a `check` 

I’ve usually have a column with a maximum length on the type, eg: `character varying(100)`

So I’m wondering, is there differences/benefits between those 2 methods ?

thank you (and sorry for being off topic)

**Comment by benjie** [comment]
Have a read of this:

https://stackoverflow.com/a/4849030/141284

**Comment by mathroc** [comment]
thank you that’s what I was looking for

**Comment by benjie** [comment]
You're welcome 😊
