### ISSUE TITLE
graphile-build-pg?

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile.github.io#162]
I just noticed when looking in the repo that there's a [`/` directory](https://github.com/graphile/graphile.github.io/tree/develop/src/pages/graphile-build-pg) containing the pages https://www.graphile.org/graphile-build-pg/settings/ and https://www.graphile.org/graphile-build-pg/security/ which are not linked from anywhere.

What's the plan for this? Should this be where all the PostGraphile internals get documented (which are necessary for writing raw plugins)?

**Comment by benjie** [comment]
Wow, blast from the past! There's no plan for this, I started documenting a few things there and then decided to use the PostGraphile docs instead. I don't think many people use `graphile-build-pg` directly, so it's probably more useful to keep documentation in the README/source code.

**Comment by ab-pm** [comment]
So better merge that into a postgraphile/internals page as discussed at https://github.com/graphile/graphile-engine/issues/522, I see. Working on a PR already.

**Comment by benjie** [comment]
Awesome; close this if appropriate :+1:

**Comment by benjie** [comment]
Closing this for now.
