### ISSUE TITLE
News page

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile.github.io#163]
This section

https://github.com/graphile/graphile.github.io/blob/95cc2246df7ae6b42d68afdd8feb908a9501a2e4/src/pages/news/index.md#L58-L114

seems duplicated from the /postgraphile/index.md page, and imo doesn't really fit on the news page. Maybe have some kind of Twitter plugin showing the latest @graphilehq tweets instead?

**Comment by benjie** [comment]
cc @jemgillam

**Comment by jemgillam** [comment]
That's a good idea, thanks! 

I've been thinking about overhauling this page somewhat and finding somewhere for our [Medium content](https://medium.com/graphile) to live. It doesn't fit in with the news about the PostGraphile releases, but also we should own our content. Any suggestions are most welcome 😄

**Comment by benjie** [comment]
I agreed so I've removed it :+1:
