### ISSUE TITLE
Recipe suggestion for calling postgres function from application layer

### ISSUE THREAD

**Issue by DamodarSojka** [graphile/graphile.github.io#233]
Question:
"I want to call postgres function with security definer from within an application layer custom mutation, the user role calling this function might not have select access to the data that the postgres function creates, can I manually feed data to the selectGraphQLResultFromTable instead of giving it a query? I would imagine the right way to do it would be to move the whole logic into the postgres."

Use this in order to call and retrive the returned data:
``
const [row] = await resolveInfo.graphile.selectGraphQLResultFromTable(
                         sql.fragment`(select * from plants_private.register_account(${sql.value(args.input.email)}, ${sql.value(hashedPassword)}))`,
                            noop,
                        );
``

One other thing would be to include an example for calling multiple functions (and returning data from them) in one custom migration.
Also, noop has to be provided due to typing, while in fact it seems it might not be needed.

**Comment by benjie** [comment]
Integrated.

> One other thing would be to include an example for calling multiple functions (and returning data from them) in one custom migration.

That definitely shouldn't be done with `selectGraphQLResultFromTable` - see the updated content.

> Also, noop has to be provided due to typing, while in fact it seems it might not be needed.

Yeah; that's deliberate. It's normally an omission when you don't include the callback, so marking it as always required helps to catch these accidental bugs at the slight cost of having to add a noop in rare circumstances.

**Comment by benjie** [comment]
https://github.com/graphile/graphile.github.io/commit/319576df7d0dab531b4aaf92196512c12ceb716e
