### ISSUE TITLE
Triangle elements create a scroll bar on site

### ISSUE THREAD

**Issue by zaccolley** [graphile/graphile.github.io#33]
![screenshot from 2018-02-17 09-36-11](https://user-images.githubusercontent.com/2591901/36339841-08006d44-13c6-11e8-9ca6-dd097d00e818.png)

The triangle element that goes before sections creates a scroll bar.

Think it's cause of the 100vw size which doesn't take into account the scroll bar.

**Comment by benjie** [comment]
👋 Hi Zac! Thanks for the heads up, I don't notice this kind of thing because I've got scrollbars hidden on OSX.
