### ISSUE TITLE
Explain how PostGraphile/schema is deployed to production

### ISSUE THREAD

**Issue by JofArnold** [graphile/graphile.github.io#43]

**Comment by benjie** [comment]
Would be good to give a "Heroku Button" example that people can just press.

**Comment by garcianavalon** [comment]
I'm using postgraphile on GCP (app engine + cloud sql) with automatic deployment from GitLab CI, I could contribute a step by step guide (I actually need to do this internally anyway...). 

@benjie where would it be the right place? Guides section?

**Comment by benjie** [comment]
Awesome; yes please! Guides section - exactly. It'd be somewhere like `graphile.org/postgraphile/deployment-gcp/` and then we'll have a bunch of `deployment-*` pages over time :+1:

**Comment by garcianavalon** [comment]
In the mean time, I've opened an issue with some notes on how to deploy on GCP https://github.com/graphile/graphile.github.io/issues/161

**Comment by benjie** [comment]
Guides shipped to the documentation website for Heroku, Lambda, GCP and Docker.

Improvements are very welcome!
