### ISSUE TITLE
Document implementing custom types via plugins

### ISSUE THREAD

**Issue by ndarilek** [graphile/graphile.github.io#63]
I'm building a platform where clients submit orders for writing and copywriters fill them. We're likely to use HTML rather than text to capture formatting in the orders and attempts. Naturally I want to sanitize that HTML both before it reaches the database and, for extra safety, before it is returned to the user.

There is, to my knowledge, no HTML sanitization feature in Postgres (please correct me if I'm wrong.) There is, however, a sanitize-html NPM package.

What I'd like to do is create a type, `HTML`, that is for all intents and purposes a string/text. Before that text is written to the database, or rendered in a query response, it is passed through `sanitizeHtml(text)` or something similar.

I'll happily package this as a plugin and contribute it back, but either having it documented or knowing which areas of the docs to focus on would be helpful. Thanks!

**Comment by benjie** [comment]
Closed in https://github.com/graphile/graphile.github.io/pull/141
