### ISSUE TITLE
Recipe: Single mutations that create multiple rows in different tables

### ISSUE THREAD

**Issue by zth** [graphile/graphile.github.io#66]
Here's a recipe for single mutations that create multiple rows in different tables. Feel free to review and change as you see fit. I hope it's understandable, and thank you for the help with understanding how this works.

## Single mutations that create multiple rows in different tables
Occasionally you'll want to create a bunch of rows in different tables in a single mutation. Here's an example of how to do that. 

Pretend we're registering quiz entries, and we want to store each answer in its own table as we want to be able to operate on the answers independently later.

This means we want:
1. A mutation that takes input data for inserting one quiz entry and multiple answers.
2. A function that inserts a new quiz entry, inserts an answer for each answer provided in the input data, and connects each answer to the created quiz entry.
3. Finally, we want the function to return the inserted quiz entry itself.

Here's the setup:

```sql
create table quiz_entry (
  id serial primary key,
  user_id text not null references users(id),
  created_at timestamp default now() not null,
  updated_at timestamp default now() not null,
  quiz_id integer not null references quiz(id) /* This table models the quiz taken */
);

create table quiz_entry_answer (
  id serial primary key,
  user_id text not null references users(id),
  quiz_entry_id integer not null references quiz_entry(id),
  question text not null,
  answer integer,
  created_at timestamp default now() not null,
  updated_at timestamp default now() not null
);

/**
 * This type is used for input in the mutation
 */

create type quiz_entry_input as (
  question text,
  answer integer
);

create function add_quiz_entry(
  quiz_id integer,
  answers quiz_entry_input[]
)
  returns quiz_entry as $$
  declare
    q quiz_entry;
    a quiz_entry_answer;
  begin
    insert into quiz_entry(user_id, quiz_id)
      values(current_user_id(), quiz_id)
      returning * into q;

    foreach a in array answers loop
      insert into quiz_entry_answer(user_id, quiz_entry_id, question, answer)
        values (current_user_id(), quiz_id, a.question, a.answer);
    end loop;
    return q;
  end;
$$ language plpgsql volatile strict;
```

There! This will create a mutation that takes a quiz id and a series of answers in the shape of `[{ question: string, answer: number }]`. It'll add a new quiz entry, add all answers, connect them, and then finally return the created quiz entry.

**Comment by benjie** [comment]
Thanks! You can now see this example on our website:

https://www.graphile.org/postgraphile/function-gallery/#Custom_mutations__Insert_multiple_records
