### ISSUE TITLE
Subscriptions docs should tell you to use a different GraphQL client

### ISSUE THREAD

**Issue by benjie** [graphile/graphile.github.io#68]
PostGraphile's GraphiQL doesn't currently support subscriptions.

HT @mattmeye

**Comment by garcianavalon** [comment]
I think this one doesn't apply anymore, it currently does and its documented how to test subscriptions with it [here](https://github.com/graphile/graphile.github.io/blob/develop/src/pages/postgraphile/subscriptions.md#testing-your-subscription-with-graphiqlgraphql-playground)

**Comment by benjie** [comment]
:+1:
