### ISSUE TITLE
Postgraphile ignores data added by SQL inserts?

### ISSUE THREAD

**Issue by Timmmm** [graphile/graphile.github.io#72]
This might be an obvious newbie issue, but it seems *really* weird to me. I created a database, and started postgraphile. I then opened GraphiQL and added a row to a table using a mutation. Querying the data returns it correctly.

However, if I add data directly via an SQL insert, somehow it is always ignored by GraphiQL - it only returns data that was added by GraphiQL. I've inspected the table via SQL and I can't see anything to distinguish the rows. I even logged the query that GraphiQL runs and verifies that it returns all the data as JSON (including the data added via SQL) and there's no obvious different between them. Yet GraphiQL somehow filters out the data that I added via SQL.

Is this expected? If not I can try and give reproduction instructions. It's super weird though so if it is expected you should probably document it at the start of the documentation somewhere.

**Comment by benjie** [comment]
That's definitely not expected (and I'm not even sure how it can be possible...). Are you certain that they're talking to the same database from PostGraphile and from your SQL insert? When you inspect the rows that you inserted through SQL do you see the rows that you inserted through GraphiQL?

**Comment by Timmmm** [comment]
Ugh so it turns out that pasting things into psql doesn't work at all well, and one of my `commit;`'s got lost so I was still within an atomic block. Unfortunately the prompt doesn't give you any indication of this and everything seems to work normally (except GraphiQL can't see the data I added of course. :-/).

Sorry for wasting your time!

**Comment by benjie** [comment]
Ah; thanks for reporting back 👍
