### ISSUE TITLE
graphQL middleware tests hangs

### ISSUE THREAD

**Issue by bejito** [graphile/graphile.github.io#80]
I am following the pattern described in here: https://www.graphile.org/postgraphile/testing-jest/#testing-the-graphql-middleware

Using this, the tests never end and cause a `Jest did not exit one second after the test run has completed.`

So even if I have nothing in the tests, not even calling the `runGraphQLQuery`, the test suite hangs in the end. After some investigation, this seems to be due to `createPostGraphileSchema`: if I run only this, the tests never end.
Looking at the DB connections, it seems there is a connection that remains open on an introspection query, waiting for an event ` Client: ClientRead`

if I run the tests with the flag `--forceExit` the test suite successfully ends. However, I would prefer not doing so as this could hide other issues in the future.

I was wondering if you has the same behavior and how you did get around this.

**Comment by benjie** [comment]
It sounds like this line in the teardown is not being called:

```
    await rootPgPool.end();
```

Can you confirm?

**Comment by bejito** [comment]
This line is getting called, and when I check the `rootPgPool.totalCount` after wards, I have 0 which is good.
Before calling `end`, the pool has 2 connections to the database, but if I look at my DB I see 3 of them... And after the `end`, the 2 connections from the pool get closed but there is a 3rd one that remains open

**Comment by benjie** [comment]
Do you happen to have your test schema in watch mode?

**Comment by bejito** [comment]
I have the same behavior whether or not I have `watchPg` set in my options

**Comment by benjie** [comment]
Hmmm. Basically it seems like there’s a pgClient hanging around somehow. That’s why I thought it might be watch mode, as that uses a dedicated pgClient. Other than that, I cannot think what it might be. Are you using the supporter plugin?

**Comment by bejito** [comment]
Well, I think I got the issue:

The main file of my repo is:
```typescript
import express from 'express';

import { logger } from './monitoring';
import gql from './gql';

const { PORT } = process.env;

const app = express();
app.use(gql);

app.listen(PORT, () => logger.info(`Listening on port ${PORT}`));
```

And the gql file contains:
```typescript
import { postgraphile, PostGraphileOptions } from 'postgraphile';

import pgSimplifyInflectorPlugin from '@graphile-contrib/pg-simplify-inflector';

export const config: PostGraphileOptions = {
  cors: true,
  showErrorStack: true,
  dynamicJson: true,
  appendPlugins: [pgSimplifyInflectorPlugin],
};

export const schemas: string[] = ['schema'];

export default postgraphile(process.env.DB_CONNECTION_URL, schemas, config);


```
At first the express server was on the same file (like in here: https://www.graphile.org/postgraphile/testing-jest/#testing-the-graphql-middleware), so it was getting executed and it was hanging, but this was caught by the `--detectOpenHandles`, so I extracted it to another file.

However, there is another open handle that is in 
```typescript
postgraphile(process.env.DB_CONNECTION_URL, schemas, config);`
```
which also gets executed  when I import the config from this file.

Making this last line into 
```typescript
export default () =>
  postgraphile(process.env.DB_CONNECTION_URL, schemas, config);
```

seems to fix my issue 👍 

Thanks
